spring:
  profiles: aws-beanstalk

externals:
  apis:
    doctor-api:
      host: "http://doctor-api-env.eba-rycnwmxd.us-east-1.elasticbeanstalk.com"
      port: "80"
    patient-api:
      host: "http://patient-api.us-east-1.elasticbeanstalk.com"
      port: "80"

