spring:
  profiles:
    active: local
#  h2:
#    console.enabled: true
#    console.path: /h2-console
#    console.settings.trace: false
#    console.settings.web-allow-others: false
#  datasource:
#    url: jdbc:h2:mem:mydb # jdbc:h2:file:/data/demo if persistence is required for file
#    username: root
#    password: demo
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  data:
    mongodb:
      uri: mongodb+srv://root:root@yantracloudappcluster.gn3di.mongodb.net/doctor-everywhere-app??retryWrites=true&w=majority
server:
  port: '8081'

springdoc:
  swagger-ui:
    path: swagger-ui.html

logging:
  level:
    web: TRACE
    org:
      springframework:
        web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
